-- --------------------------------------------------------
-- 主机:                           127.0.0.1
-- 服务器版本:                        11.3.0-MariaDB - mariadb.org binary distribution
-- 服务器操作系统:                      Win64
-- HeidiSQL 版本:                  12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- 导出 psa_db 的数据库结构
CREATE DATABASE IF NOT EXISTS `psa_db` /*!40100 DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci */;
USE `psa_db`;

-- 导出  表 psa_db.candidate 结构
CREATE TABLE IF NOT EXISTS `candidate` (
  `candidate_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `gender` char(1) NOT NULL,
  `age` smallint(6) NOT NULL DEFAULT 0,
  `education` varchar(100) NOT NULL,
  `skillset` varchar(1000) NOT NULL,
  PRIMARY KEY (`candidate_id`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- 正在导出表  psa_db.candidate 的数据：~30 rows (大约)
INSERT INTO `candidate` (`candidate_id`, `name`, `gender`, `age`, `education`, `skillset`) VALUES
	(32, 'Yunjae Oh', 'F', 26, 'Bachelor of Business Information Systems, Management Information Systems, General', 'Adobe Photoshop, Adobe Premiere Pro, Quality Assurance, User Interviews, Design Library, Information Architecture, Rapid Prototyping, Wireframing, UX Research, Usability Testing, User Experience (UX), MySQL, Java, React.js, Business Strategy, Python (Programming Language), HTML, Cascading Style Sheets (CSS), Figma (Software), PHP'),
	(33, 'Marcus Yeo', 'M', 27, 'Information Systems, E-Commerce/Electronic Commerce + Digital Innovation', 'Software Development, Start-ups, Information Systems, Leadership, Team Management'),
	(34, 'Yi Xuan Tong', 'F', 27, 'Bachelor of Social Sciences with Honours, Communications and New Media', 'Social Media Marketing, Creative Writing, Adobe Photoshop, Adobe Illustrator, Teamwork, Basic HTML/CSS/Javascript, Microsoft Excel, Microsoft Word, Microsoft PowerPoint'),
	(35, 'Shermaine Tay', 'F', 26, 'Bachelor of Science , Major in Marketing with a Minor in Entrepreneurship', 'Social Media, Customer Service, Microsoft Office, Photography, Teamwork, Event Planning, Analytical Skills, Assisting Others, Adobe Photoshop, Microsoft PowerPoint, Microsoft Word, Microsoft Excel, Editing, Public Speaking'),
	(36, 'Ryan Ong', 'M', 22, 'Bachelor of Business Administration - BBA', 'Venture Capital, Event Planning, Student Engagement, C++, Project Management, Microsoft Word, Python (Programming Language)'),
	(37, 'Julaina Jaffar', 'F', 30, 'Bachelor\'s degree, Hospitality Business', 'Event Management, Customer Service, Teamwork, Presentation Skills, Facilitation, Microsoft Office, Multilingual Communication, Sponsorship, Public Relations, PowerPoint, Communication, Fundraising, Partner Relationship Management, Social Media, Collaborator, Community Building, Data Analysis, Data Visualization, Stakeholder Engagement'),
	(38, 'Denise Teo JiaQi', 'F', 25, 'Master of Arts - MA, Digital Management', 'Program Direction, Leadership, Youth Mentoring, Mentoring, Hosting Services, Live Streaming, Social Media Consulting, Cross-functional Team Leadership, Content Creation, Organization Skills, Agile Project Management, Online Content Creation, Start-ups, Community Building, Team Management, Operations Management, Dance, Event Management, Film Production, Social Media, Production Planning, Project Management, Program Management, Public Speaking, Community Management, Video Production'),
	(39, 'Fauzi Aziz', 'M', 35, 'Bachelor of Arts (Honours), Theatre Studies', 'Acting, Creative Writing, Film Editing, Film Production, Final Cut Pro, Mac OS, Microsoft Office, Radio Broadcasting, Social Media, Sociology, Teaching, Theatre, Microsoft Excel, Event Management, Public Speaking, Event Planning, Public Relations, Social Media Marketing, Management'),
	(40, 'Brenda Tan', 'F', 30, 'Bachelor of Arts (Honours), Communications and New Media, Communication and Media Studies', 'Social Media, Video Editing'),
	(41, 'Samantha Ngain', 'F', 31, 'Communication and Information, Radio and Television Broadcasting, Public relations', 'Pitching Ideas, Team Management, Creative Ideation, Project Management, Content Strategy, Social Media Marketing, Program Facilitation, Digital Marketing, Social Media, Teamwork, Customer Service, Interacting with people'),
	(42, 'Jia Hui Chow', 'M', 30, 'Bachelor of Business Administration (BBA), Business Administration and Management, General', 'Public Speaking, Microsoft Office, Social Media Communications, Project Management, Sketching, Social Media, Content Marketing, Content Strategy, Microsoft PowerPoint, Microsoft Excel, Microsoft Word, Teamwork, Leadership, Management, Social Media Content Creation, Online Content Creation, Singing'),
	(43, 'Wei Liang Lim', 'M', 22, 'Executive Master, Leadership, Strategy and Innovation', 'Microsoft Office, Microsoft Excel, Management, Microsoft Word, PowerPoint, Public Speaking, Research, Project Management, Leadership, Customer Service, Problem Management, Marketing Strategy, Market Research, C#'),
	(44, 'Cameron Belliston', 'F', 23, 'Bachelor of Social Sciences', 'Advertising, Public Relations, Copywriting, Theatre, Marketing, Corporate Communications, Media Relations, Digital Marketing, Adobe Photoshop, Adobe Illustrator, Adobe Premiere Pro, Microsoft PowerPoint, Microsoft Word, Microsoft Outlook, Leadership, Scriptwriting, Social Psychology'),
	(45, 'Jessica Chong', 'F', 26, 'High School Diploma, Chinese Media and Communications', 'Microsoft PowerPoint, Mandarin, Adobe Photoshop, Short Films, Adobe Premiere Pro, Adobe Illustrator, Adobe InDesign, Hokkien, English, Audacity, Cheerleading, Video Production, Radio Production, Social Media Marketing'),
	(46, 'Bolipan Imrungraung', 'M', 26, 'Master, Sport and Fitness Administration/Management', 'Writing, Sports Industry, Creative Content Creation, Photography, Thai, English'),
	(47, 'Rayson Tan', 'M', 25, 'Diploma of Education, Entrepreneurial and Small Business Operations', 'Business Strategy, Pitching Ideas, Product Development, Business Development, Client Relations, Digital Marketing'),
	(48, 'Chong Ing Kai', 'M', 25, 'Diploma, Engineering with Business', 'Problem Solving, Team Management, Entrepreneurship, Product Development, 3D Printing, Soldering, Curriculum Development, Laser Cutting, SMT'),
	(49, 'Aik Heng Ch\'ng', 'M', 30, 'Diploma of Education, Biomedical Sciences, General', 'Accounting, Analytical Skills, Entrepreneurship, Photography, New Business Development, WordPress, Fundraising, Software as a Service (SaaS), Sales, English, Research, Training, Problem Solving, Leadership, Communication'),
	(50, 'Adam Ihsan', 'M', 32, 'Master of Business Administration', 'Project Management, Leadership, Public Speaking, Solidity'),
	(51, 'Emmanuel Baltazar II', 'M', 33, 'Bachelor Science in Entrepreneurship, Business', 'Negotiation, Business Strategy, Project Management, Marketing'),
	(52, 'Angie Ang', 'F', 31, 'Master\'s Degree, LLM Legal Practice Course', 'Skill Development, Relationship Development, Business Administration, Interpersonal Skills, Communication, Application Development, Coaching, Negotiation, Cross-functional Team Leadership, Microsoft PowerPoint, Public Relations, Public Speaking, People-oriented, Start-ups, Multilingual, Editing, Legal Writing, Research, Social Media, Legal Research, Event Management, Due Diligence, Legal Advice, Corporate Finance, Corporate Law, Corporate Governance, Youth Development, Microsoft Office, Microsoft Word, Mentoring, Teamwork, Personal Development, Team Leadership, Leadership'),
	(53, 'Sotirios P. Seridis', 'M', 34, 'Online Product Management Course, Product Management', 'Search Engine Optimization (SEO), Google Ads, SEM, Digital Marketing, Digital Strategy, PPC, Web Analytics, SEO, Google Adwords, E-commerce, Google Analytics, Social Media, Search Advertising, Landing Page Optimization, Social Media Marketing, Marketing Strategy, Digital Media, Online Advertising, Conversion Optimization, Keyword Research, Online Marketing, Marketing Communications, Marketing Research, SPSS, Python, Strategy'),
	(54, 'Chelsia Goh', 'F', 35, 'Bachelor of Business Administration - BBA', 'Venture Capital, Entrepreneurship, Persuasive Writing, Managerial Finance, Corporate Finance, Microsoft PowerPoint, Microsoft Excel, Python (Programming Language), Time Management, Leadership, Team Management, Microsoft Office, Team Leadership, Communication, Teamwork, Organization Skills, Facilitation, Motivational Speaking, Public Speaking, Social Innovation'),
	(55, 'Sean Tan', 'M', 35, 'Information Systems, Information Systems', 'Web Development, Leadership, Entrepreneurship, MongoDB, JavaScript, Express.js, React.js, Supabase, Next.js, Prisma, trpc, TypeScript, GitHub, Tailwind CSS, MUI, Pardot, Marketing Operations, Operations Management, Digital Marketing, Facebook Marketing, Marketing Strategy, WordPress, HubSpot Marketing Hub, Google Analytics, Microsoft Excel'),
	(56, 'Qing Feng Lee', 'M', 25, 'Master of Business Administration - MBA', 'PCR, Molecular Biology, Cell Culture, Lifesciences, Cell Biology, Genomics, qPCR, Microbiology, Genetics, DNA, Biotechnology, Cell, Assay Development, DNA sequencing, Immunology, RT-PCR, DNA Sequencing, Life Sciences, Polymerase Chain Reaction (PCR), Medical Devices'),
	(57, 'Sarah Yeap', 'F', 31, 'Bachelor of Commerce - BCom, Marketing and Management', 'Marketing, Microsoft Office, Social Media, Social Media Marketing, Microsoft Excel, Microsoft Word, Microsoft PowerPoint, Management'),
	(58, 'Adam Flinter', 'M', 36, 'Master of Business Administration - MBA', 'Digital Media, Digital Strategy, New Media, Social Media, Editorial, Content Strategy, Journalism, Web Content Management, Digital Marketing, SEO, Publishing, Integrated Marketing, CMS, Public Relations, Marketing Communications, Social Media Marketing, Copywriting, Online Advertising, Social Networking, Newspapers, Online Journalism, Photoshop, Writing'),
	(59, 'Jeremy Ong', 'M', 44, 'Bachelor of Science, Banking & Finance', 'Finance'),
	(60, 'Saif Siddiqui', 'M', 32, 'Master of Business Administration (MBA), Strategy', 'Financial Modeling, Private Equity, Valuation, Finance, Strategy, Due Diligence, Portfolio Management, Financial Analysis, Design Thinking, Innovation Management, Business Innovation, SQL, Tableau, Microsoft PowerPoint'),
	(61, 'Sharon Sim', 'M', 49, 'School of foreign Service, Developmental Economics', 'Emerging Markets, Capital Markets, Equities, Valuation, Fixed Income, Investment Banking, Bloomberg, Hedge Funds, Derivatives, Entrepreneurship, Financial Markets, Equity Research, Portfolio Management, Structured Products, Trading, Financial Modeling, Investments, Alternative Investments, Asset Management');

-- 导出  表 psa_db.hr_users 结构
CREATE TABLE IF NOT EXISTS `hr_users` (
  `hr_uname` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  PRIMARY KEY (`hr_uname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- 正在导出表  psa_db.hr_users 的数据：~4 rows (大约)
INSERT INTO `hr_users` (`hr_uname`, `password`) VALUES
	('lisz', 'lisz'),
	('lixt', 'lixt'),
	('sunyt', 'sunyt');

-- 导出  表 psa_db.jobs 结构
CREATE TABLE IF NOT EXISTS `jobs` (
  `jobid` int(11) NOT NULL AUTO_INCREMENT,
  `jobname` varchar(200) NOT NULL,
  `joblink` varchar(150) NOT NULL,
  `jobcat` varchar(100) NOT NULL,
  `closing` timestamp NOT NULL,
  `jobdesc` varchar(2000) NOT NULL,
  PRIMARY KEY (`jobid`)
) ENGINE=InnoDB AUTO_INCREMENT=996 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- 正在导出表  psa_db.jobs 的数据：~100 rows (大约)
INSERT INTO `jobs` (`jobid`, `jobname`, `joblink`, `jobcat`, `closing`, `jobdesc`) VALUES
	(896, 'UX Technical Lead and Designer', '/en/job/492603/ux-technical-lead-and-designer', 'Infocomm Technology', '2023-10-31 01:30:00', ' Possess a degree in any discipline. 2 years of UX design experience. Preference will be given to candidates who have experience designing large and complex systems. Expertise in designing tools like Sketch, InVision, Adobe Photoshop, Adobe Illustrator Understands the UX development lifecycle from supporting product conceptualisation to information architecture and user usability research to wireframing and eventual delivery Awareness of user experience trade-offs and interactions optimisation to translate conceptual requirements to sustainable designs Excellent communication, stakeholder management and presentation skills Candidates with prior domain experience in logistics or shipping related applications will have an added advantage Familiarity with the following front-end development technologies is a plus  HTML5 & CSS  JavaScript (JQuery, D3, Angular/Angular2)  Springboot development framework  Mobile development with Android or iOS and related UX design considerations'),
	(897, 'HR Recruitment Coordinator (6 months contract with possible extension/conversion)', '/en/job/493386/hr-recruitment-coordinator-6-months-contract-with-possible-extensionconversion', 'Human Resource', '2023-10-31 07:55:00', ' Possess at least NITEC qualifications  At least 1 year relevant work experience in a resourcing function, in particular the end-to-end recruitment process. Proficient in MS Office and prior experience using Peoplesoft Must be a good team player and able to work independently  Strong organizational skills with the ability to deal with high volume of work  Results driven and meticulous\n'),
	(898, 'Accounts Executive (Accounts Receivable)', '/en/job/493423/accounts-executive-accounts-receivable', 'Finance', '2023-12-31 07:55:00', ' Possess Diploma in Accountancy or equivalent  Have at least 1 year of Book keeping experience and/or experience in AR / AP  Must be meticulous and detailed  Candidates applying for the above position should also possess strong analytical and communication skills, as well as team spirit and the ability to excel under pressure.\n'),
	(899, 'Operations Supervisor (Gate Operations)', '/en/job/493420/operations-supervisor-gate-operations', 'Operations', '2023-10-20 07:55:00', ' At least 3   level credits, NITEC, ITC or equivalent Able to work on shift'),
	(900, 'Senior Civil Engineer (Construction Project Management)', '/en/job/493421/senior-civil-engineer-construction-project-management', 'Engineering', '2023-12-31 07:55:00', 'Degree in Civil Engineering or Building\nGood knowledge and experienced in building related works such as civil engineering, structural, architectural, building repair, carpentry, partition, A&A, renovation, plumbing works etc.\nExperience in construction of building projects with architectural finishes work is preferred\nFamiliar with planning software(s) such as Primavera and MS Project\nPossesses excellent communication and interpersonal skills.\nMust have initiative and drive to resolve site issues to achieve project success.\nProficient in MS Work & Excel and drafting of letter.'),
	(901, 'Civil Senior Technical Officer (Construction Project Management)', '/en/job/493422/civil-senior-technical-officer-construction-project-management', 'Engineering', '2023-12-31 07:55:00', 'Diploma in Civil Engineering or Construction Engineering\nAt least 5 years of Project Management experience in a Construction or related industry.\nKnowledge of Building Information Modeling will be an advantage\nPossesses excellent communication and interpersonal skills.\nProficient in MS Work & Excel.'),
	(902, 'Accountant (FP&A)', '/en/job/493023/accountant-fpa', 'Finance', '2024-02-28 18:45:00', ' A good Accountancy degree with at least 1 year of working experience Self-motivated, highly curious, possess a keen eye for details and willing to be \'hands-on\' when needed Possess solid analytical and effective business partnering skills to liaise with people of all levels, including JV partners and Senior Management\nCandidates with relevant experience could be considered for Assistant Finance Manager role. The job title will commensurate with relevant experience.'),
	(903, 'Assistant Operations Executive (Depot Management)', '/en/job/493417/assistant-operations-executive-depot-management', 'Operations', '2023-12-31 07:55:00', 'Diploma in Logistics / Supply Chain Management. Other disciplines with experience in logistics operations management preferable in 3rd party logistics, distribution or manufacturing environment will also be considered\nProficiency in MS Office\nAbility to work independently \nGood communication skills\nWilling to work on a 5.5 days work schedule'),
	(904, 'Operations Supervisor/Assistant Operations Executive (Sembawang Wharves)', '/en/job/493416/operations-supervisorassistant-operations-executive-sembawang-wharves', 'Operations', '2023-12-31 07:55:00', '  Level, NITEC or Diploma in Logistics / Supply Chain Management. Other disciplines with experience in logistics operations management preferable in 3rd party logistics, distribution or manufacturing environment will also be considered\nProficiency in MS Office\nAbility to work independently \nGood communication skills\nWilling to perform 12 hours shift'),
	(905, 'Operations Supervisor (ChemCare)', '/en/job/493397/operations-supervisor-chemcare', 'Operations', '2023-10-07 07:55:00', ' Higher NITEC / NITEC in any discipline Possess Class 3 or Class 3A license\nThe following will be highly valued: Knowledge and experience in Dangerous Goods regulation and inspection protocols Knowledge and experience of billing procedures  Experience in conducting inspections and preparing detailed reports Good organizational and time management skills, with the ability to prioritize tasks effectively Strong attention to detail and accuracy in recording and reporting information Proficient in using computer applications for data entry and report preparation'),
	(906, 'Container Equipment Specialist (Yard Crane)', '/en/job/493308/container-equipment-specialist-yard-crane', 'Operations', '2023-10-05 07:55:00', ' Able to work at heights  work on rotating shift'),
	(907, 'Manager/Senior Manager (Procurement)', '/en/job/493415/managersenior-manager-procurement', 'Procurement', '2023-12-31 07:55:00', 'Bachelor\'s degree.\n5-8 years experience in procurement of corporate and spares categories, and a focus on digital, marketplace and e-procurement.\nExperience with e-procurement, SRM, KYS, spend analysis and compliance monitoring.\nStrong stakeholder engagement and effective influencing and change management skills\nStrong analytical and problem-solving skills.\nAbility to manage multiple projects simultaneously.\nEnergetic, resourceful, self-motivated and resilient.\nAbility to work independently and as part of a team.\nCompetent in negotiations and contract knowledge'),
	(908, 'Assistant Operation Executive (Pasir Panjang Automobile Terminal)', '/en/job/493414/assistant-operation-executive-pasir-panjang-automobile-terminal', 'Operations', '2023-12-31 07:55:00', 'Diploma in Logistics / Supply Chain Management. Other disciplines with experience in logistics operations management preferable in 3rd party logistics, distribution or manufacturing environment will also be considered\nProficient in MS Office\nAble to work independently\nGood communication skills\nWilling to perform 12 hours shift'),
	(909, 'Finance Manager/Senior Finance Manager (Logistics)', '/en/job/493413/finance-managersenior-finance-manager-logistics', 'Finance', '2023-12-31 07:55:00', 'Possess a degree in Accountancy and at least 10 years experience of relevant experience, of which at least 5 years\' are in the logistics industry\nStrong analytical skills and sharp commercial and business acumen\nGood business partnering skills\nExcellent communication skills - both written and verbal'),
	(910, 'Assistant / Deputy Manager / Manager (Port+ Commercial)', '/en/job/493303/assistant-deputy-manager-manager-port-commercial', 'Operations, Commercial', '2023-12-31 07:55:00', 'Degree in any discipline\nCritical thinking and writing skills\nReasonable numeric literacy\nBasic level of data intelligence and curiosity preferred\nGood communication and interpersonal skills\nAdaptability and resilience; able to react nimbly to dynamic changes in customer demands and work scope\nHas keen interest to learn'),
	(911, 'Manager (Talent Acquisition)', '/en/job/493412/manager-talent-acquisition', 'Human Resource', '2023-10-31 07:55:00', ' Possess a Degree in any discipline or equivalent  At least 8 to 10 years of relevant experience with industry exposure to B2B organisations  Strong communication and interpersonal skills  Track record in supporting senior stakeholders on their business needs Possess drive and able to thrive in a dynamic environment  Results-driven and takes ownership and accountability  Experience with end-to-end HR programmes; including but not limited to leading projects,   campus recruitment fairs, recruitment branding  Strong business acumen and analytical skills Proactive and a team player'),
	(912, 'Company Driver', '/en/job/493410/company-driver', 'Admin', '2023-12-31 07:55:00', ' Possess Class 3 & Class 4 driving licence with a clean record Pleasant and polite, and be able to speak English Has prior experience driving mini bus Familiar with Singapore roads Responsible and able to maintain strict confidentiality Able to start work immediately or within short notice'),
	(913, 'Deputy Manager (Talent Acquisition)', '/en/job/493409/deputy-manager-talent-acquisition', 'Human Resource', '2023-10-31 07:55:00', '- At least 5 years\' of relevant talent acquisition experience- Good verbal, presentation, and written communication skills- Detail-oriented with strong analytical skills- A strong relationship builder who can engage effectively across diverse groups and stakeholders - Able to handle  multiple tasks concurrently in a dynamic environment- Result-driven self-starter and able to deliver in a fast-paced environment with minimal supervision- Positive, energetic and a resourceful team player- Strong interest in social media landscape and comfortable in using social media platforms for outreach- Creative and able to conceptualize compelling content with interesting and captivating visuals to engage   diverse groups- Working knowledge of editing software such as Photoshop, Adobe Premiere, Final Cut Pro etc'),
	(914, 'Accounts Assistant (AR)', '/en/job/492958/accounts-assistant-ar', 'Finance', '2023-10-31 07:55:00', 'NITEC in Accountancy or LCCI or or equivalent    \nHave at least 1 year of Book keeping experience and/or experience in AR / AP\nMust be meticulous and detailed\nCandidates applying for the above position should also possess strong analytical and communication skills, as well as team spirit and the ability to excel under pressure.'),
	(915, 'Accounts Executive (Billing)', '/en/job/493165/accounts-executive-billing', 'Finance', '2023-09-30 07:55:00', ' Diploma in Accountancy or equivalent Minimum 1 year of relevant working experience Meticulous with strong analytical skills Possess good interpersonal and organizational skills'),
	(916, 'Senior Accounts Executive/Assistant Accountant (Full Sets)', '/en/job/493407/senior-accounts-executiveassistant-accountant-full-sets', 'Finance', '2023-12-31 07:55:00', 'Diploma in Accountancy or equivalent\nMinimum 2 years of relevant working experience.\nWorking knowledge of Singapore Financial Reporting Standards\nPrior experience in process development projects would be advantageous\nWorking knowledge of Singapore Financial Reporting Standards\nMeticulous and able to work independently\nGood team player with strong interpersonal and communication skills.'),
	(917, 'Inventory Planner', '/en/job/493405/inventory-planner', 'Engineering', '2023-12-31 07:55:00', 'Requirements and skills:\nNITEC in any discipline\nProficient in Microsoft office applications like Excel and Word \nPreferably with previous experience as an inventory planner or in a similar role\nPreferably with experience in Maximo and/or Oracle Fusion'),
	(918, 'BIM Modeller', '/en/job/493404/bim-modeller', 'Engineering', '2023-12-31 07:55:00', 'Diploma in either Civil Engineering, Sustainable Urban Design & Engineering, Construction Engineering, Architecture or equivalent; or BCA Specialist Diploma in Building Information Modelling\nCompetent in AutoCAD 2D/3D and Revit\nKnowledge of e-BIM submission system\nPreferably with at least 3 years of working experience as BIM Modeller/Co-ordinator for infrastructure works and sub-utilities like drainage/sewerage'),
	(919, 'Senior Programmer Analyst / Systems Analyst / Assistant Manager (Port+)', '/en/job/493367/senior-programmer-analyst-systems-analyst-assistant-manager-port', 'Operations', '2023-12-31 07:55:00', 'Diploma or Bachelor  degree in Information System, Computer Science or related\nProven experience of one or more: Java, .NET, Angular, Spring Boot and relational databases (MS SQL, My SQL, Oracle)\nMinimum 2 years of working experience in software development, implementations and support\nKnowledge of software best practices, like Test-Driven Development (TDD) and Continuous Integration/Continuous Delivery (CI/CD)\nAble to work independently and in a team environment\nGood technical acumen\nHighly conscientious, strong analytical and problem-solving skills\nFast learner, able to multi-task and self-motivated to keep up to date with new technologies and business solutioning\nAdaptability and Resilience at work. Responsible and able to work under pressure and within timeline in a dynamic environment\nGood communication and interpersonal skills'),
	(920, 'Assistant Management Executive (Shared Services)', '/en/job/493400/assistant-management-executive-shared-services', 'Admin', '2023-10-31 07:55:00', 'Possess Diploma qualifications\nGood organization and time management skills\nAble to multi-task and work as a team player\nSelf-motivated, meticulous and willing to learn\nFluent in English, able to communicate with individuals at all levels in the organization\nProficient in Microsoft Office (Outlook, Word, Excel and Powerpoint'),
	(921, 'Senior/Principal Electrical Engineer (Energy Infrastructure)', '/en/job/493401/seniorprincipal-electrical-engineer-energy-infrastructure', 'Engineering', '2023-12-31 07:55:00', 'Degree in Electrical Engineering at least 5 years of relevant experience\nStrong knowledge of, and hands-on experience in, the design and/or maintenance of electrical building services\nFamiliar with local Code of Practices, Building and Fire Safety Regulations\nWilling to work outdoors\nThose who had completed the  igh voltage operation for engineers course will have an advantage'),
	(922, 'Deputy Manager / Manager (Green Mobility)', '/en/job/493402/deputy-manager-manager-green-mobility', 'Engineering', '2023-12-31 07:55:00', 'Degree in Electrical Engineering, Chemical Engineering, or a related field\nDeep understanding of battery chemistry, electrochemical processes, and cell design, preferably with experience in various battery chemistries (eg lithium-ion, solid-state, flow batteries)\nStrong knowledge of battery application (eg electric mobility and energy storage technologies) and lifecycle management (eg 2nd life reuse and recycling) including state of health monitoring\nExperience in battery design, modeling, testing and validation\nProficiency in battery management systems, electrical circuit design and simulation tools\nFamiliarity with industry standards and regulations related to battery safety, performance and 2nd life reuse\nExcellent problem-solving skills and ability to work in a collaborative team environment\nStrong communication skills to convey technical concepts effectively'),
	(923, 'Deputy Manager (Sustainability)', '/en/job/493399/deputy-manager-sustainability', 'Engineering', '2023-12-31 07:55:00', 'A degree in Engineering or a Science-based discipline\nRelated working experience\nPassionate about sustainability and a green future\nGood skills in idea conceptualization, communications, analysis and problem solving'),
	(924, 'Manager / Senior Manager  IT Security Governance', '/en/job/493073/manager-senior-manager-it-security-governance', 'Infocomm Technology', '2023-10-31 07:55:00', ' Bachelor  degree in Computer/Electrical/Electronics Engineering or Computer Science, preferably with industry recognized security certification such as CISSP, CRISC, CISM, etc. At least 3 years (5 years for senior manager position) of experience in IT security governance role (preferably in CII environment). Cloud Computing, Risk Assessment (Advantages) Strong problem solving and analytical skills Excellent verbal and written communication skills and customer service skills Ability to thrive under pressure, function and deliver effectively in a fast-paced environment'),
	(925, 'DevOps Engineer', '/en/job/493394/devops-engineer', '', '2023-09-30 07:55:00', ' Degree in Computing, Computer Science, Computer Engineering, Information Systems or equivalent Able to work independently; set and meet challenging personal targets; good communication skills Proficient in linux or windows scripting Strong analytical and problem-solving skills Highly conscientious, meticulous and able to multi-task Be prepared to work in a team providing 24x7 system support\nThe following will be highly valued: Knowledge in DevOps Methodologies like CI/CD, automation tools, building tools (Gradle, MSBuild) Proficient in programming (C, C#, C++, JAVA) and relational databases and related scripting (Oracle,SQL) Knowledge of software best practices, like Test-Driven Development (TDD) and Continuous Integration (CI) At least 3 years of relevant working experience\nOnly shortlisted candidates will be notified'),
	(926, 'Manager (ChemCare)', '/en/job/493391/manager-chemcare', 'Operations', '2023-12-31 07:55:00', '5-10 years of direct work experience in Logistics/Transportation or Supply Chain, Chemical background is preferable\nBachelor  degree in chemical related field.'),
	(927, 'Port+ Supervisor/ Assistant Port+ Executive (Warehouse/ Freight) [With Joining Bonus]', '/en/job/493320/port-supervisor-assistant-port-executive-warehouse-freight-with-joining-bonus', 'Operations', '2023-12-31 07:55:00', 'O\' Level, NITEC or Diploma in Logistics/ Supply Chain Management. Other disciplines with experience in logistics operations management preferable in 3rd party logistics, distribution or manufacturing environment will also be considered. \nProficiency in MS Excel\nAbility to work independently \nGood communication skills\nWilling to work on a 5.5 days work schedule'),
	(928, 'Cyber Security Network Engineer', '/en/job/493388/cyber-security-network-engineer', 'Infocomm Technology', '2023-10-31 07:55:00', ' Possess a bachelor  degree in Computer Science, Information Systems, or equivalent At least 2 years of relevant experience  Expertise across a variety of security products such as understanding of network    infrastructure, Secure Web Gateway, high volumes of network & data (e.g. Netflow, FPC),    and other attack artifacts in support of incident investigations. Proficiency with any of the following: IDPS, Network Packet Capture, Network Forensics,    Web Application Firewall and DNS security. Advanced understanding of TCP/IP, common networking ports and protocols, traffic flow,    system administration, OSI model, defense-in-depth and common security elements.'),
	(929, 'Identity and Access Management (IAM) Engineer', '/en/job/493390/identity-and-access-management-iam-engineer', 'Infocomm Technology', '2023-10-31 07:55:00', 'Possess a bachelor degree in IT, Information Security, Computer science, or a related field\nAt least 2 years of relevant experience\nWorking knowledge and experience with authentication standards and technologies such as multi factor authentication etc.\nWell-verse with hands-on knowledge of identity and access management best practices, procedures, and software solutions such as IAM, PAM, MFA, etc\nPrior experience with Windows, Lunix, AD and LDAP would be preferred'),
	(930, 'Deputy SOC Manager', '/en/job/493384/deputy-soc-manager', 'Infocomm Technology', '2023-09-30 07:55:00', 'Possess a diploma/degree in Information Systems, Cybersecurity or related disciplines\nMinimum 3 years experience in enterprise SOC operations, security consultancy or security operation\nHands-on experience on SIEM and/or SOAR will be preferred\nGood interpersonal and presentation skills\nA strong team player.\nApplicants with security certifications like GCIH and CISSP will have an added advantage'),
	(931, 'Lashing Specialist', '/en/job/493378/lashing-specialist', 'Operations', '2023-11-30 07:55:00', ' Able to lift heavy objects and work at heights Willing to work on rotating shift and outdoors'),
	(932, 'Technical Specialist (Facilities Management)', '/en/job/493229/technical-specialist-facilities-management', 'Engineering', '2023-12-31 07:55:00', ' Higher NITEC in Facility Management/Electrical/Mechanical Engineering or NITEC in Electrical/Mechanical Technology/Facility Technology (Mechanical & Electrical Services) Willing to work outdoors and at heights Experience in facilities management would be an advantage'),
	(933, '\'Administrative Assistant (Driver Pool and Office Services Unit)', '/en/job/493375/administrative-assistant-driver-pool-and-office-services-unit', 'Admin, Corporate Communications', '2024-01-31 07:55:00', 'are as follows:Driver Pool  \nManage deployment of all drivers/vehicles daily\nProcess all claims for drivers  vehicle (petrol/cash card) + staff (medical/dental claims, mileage, purchase of items)\nHire of external vehicle  coach  should the PSA vehicles be fully booked\nArrange for necessary vehicle inspections/renewal of road tax/insurance\nTo attend to accidents  support for police reports/insurance etc\nTo ensure overall cleanliness of all vehicles\nTo manage drivers leave to ensure sufficient drivers on a daily basis'),
	(934, 'Assistant Management Executive / Deputy Management Executive (Corporate Shared Services)', '/en/job/493343/assistant-management-executive-deputy-management-executive-corporate-shared-services', 'Human Resource', '2023-10-31 07:55:00', 'Diploma in any discipline good interpersonal and communications skills organised and dependable proficient in Ms Word & Excel'),
	(935, 'Assistant Human Resource Executive (Foreign Worker Administration)', '/en/job/493374/assistant-human-resource-executive-foreign-worker-administration', 'Human Resource', '2023-09-30 07:55:00', 'Possess at least a NITEC or Diploma in any discipline\nAt least 3 to 4 years of relevant HR experience dealing with foreign worker  matter\nFamiliar with the Employment Act and Foreign Work Pass Regulations/Procedures\nPossess excellent communication, interpersonal and analytical skills\nSelf-driven and positive work attitude\nDetailed and meticulous\nAbility to multi-task with good coordination and follow-up skills\nAble to work in a fast-paced environment\nProficient in MS Office applications'),
	(936, 'Assistant Manager/Deputy Manager (Enterprise Infrastructure & Services)', '/en/job/493234/assistant-managerdeputy-manager-enterprise-infrastructure-services', 'Infocomm Technology', '2023-10-31 07:55:00', 'Possess a degree in Computing, Computer Science/Engineering or IT At least 5 years of IT infrastructure support Experience in maintaining and managing Microsoft technologies - Azure cloud services,Office365, Active Directory   (ADFS, DHCP, CA, DNS, RMS), Exchange Service (O365), System Center IT Operations Management Hosting Platforms (MS Hyper-V, VMWare, Azure)  Remote Access Service  System Management  Unified Communications  Network (Wireless/LAN), NAC, 802.1x services Other Services (File, Print and Endpoint protection service)  Possess strong analytical and troubleshooting skills Good interpersonal and communication skills  Ability to work independently and a good team player Preferably with certification in Microsoft Certified: Azure Administrator Associate, Teams Administrator or more'),
	(937, 'Workplace Safety & Health Officer', '/en/job/492857/workplace-safety-health-officer', 'HSS SEA', '2023-10-31 04:55:00', 'Degree in Engineering or Environmental, Health and Safety or other relevant subjects\nPreferably a MOM Registered WSH Officer\nMinimum 2-3 years of relevant experience in Occupational Safety, Health and Environmental field\nGood knowledge of Government Regulations relating to Occupational Safety, Health and Environmental areas\nFamiliar with OSH/ ISO documentation\nGood communication & writing skills is required\nHas a strong interest in data analytics\nMust be able to work under pressure\nCandidates with experience in Industrial Hygiene will be added advantage'),
	(938, 'Deputy Manager - Insurance', '/en/job/493371/deputy-manager-insurance', 'Finance', '2023-12-31 07:55:00', ' Degree/Diploma in Accountancy, Business or a related field\n Preferably with at least 3 years of relevant insurance experience\n Possess strong analytical and communication skills\n Prior experience in leading or supervising a small team \n Proactive and resourceful team player'),
	(939, 'CLAIMS EXECUTIVE (6 months contract with possibility for conversion/extension)', '/en/job/493372/claims-executive-6-months-contract-with-possibility-for-conversionextension', 'Finance', '2023-12-31 07:55:00', 'Diploma/Degree in any discipline\nMin 1 years of relevant work experience in handling staff related in general claims and other classes of insurance-related claims\nMeticulous, organised and systematic'),
	(940, 'Civil Technical Officer (Building Management)', '/en/job/492908/civil-technical-officer-building-management', 'Engineering', '2023-12-31 07:55:00', 'Diploma in Civil Engineering, Construction Engineering, Building or Facility Management'),
	(941, 'Assistant Management Executive (HRS)', '/en/job/493364/assistant-management-executive-hrs', 'Human Resource, Admin', '2023-11-30 07:55:00', ' NITEC/Diploma in any discipline\n Good organization and time management skills\n Able to multi-task and work as a team player\n Self-motivated and able to work with minimal supervision\n Able to communicate with individuals at all levels in the organization\n Proficient in Ms Word & Excel'),
	(942, 'Senior Procurement Executive / Assistant Manager (Engineering Procurement)', '/en/job/493361/senior-procurement-executive-assistant-manager-engineering-procurement', 'Procurement', '2023-09-30 07:55:00', 'Possess a degree with 2-3 years of experience in sourcing and procurement\nGood understanding of strategic sourcing, tendering process, contract management, contract negotiation and contract governance\nExcellent communication skills, with willingness to learn negotiation and effective influencing skills\nAble to establish good working relationships with internal and external stakeholders so as to meet PSA  business needs \nGood time management skills, able to work effectively towards given timelines\nEnergetic, resourceful and self-motivated\nCandidates with experience in the procurement of Engineering goods and services are preferred\nExperience with e-procurement software (e.g Oracle Fusion, SAP Ariba, Coupa, GEP etc.) would be an added advantage \nProficient in MS Office'),
	(943, 'Dormitory Supervisor', '/en/job/493357/dormitory-supervisor', 'Operations', '2023-12-31 07:55:00', ' Minimum Sec 2 (Express) or Sec 3 (Normal) or equivalent Willing to work on rotating shifts'),
	(944, 'Tax Specialist', '/en/job/493353/tax-specialist', 'Finance', '2023-10-31 07:55:00', 'Possesses a good degree in Accounting, Finance, Tax or other business-related fields with a Professional Qualification (as recognized by SIATP and/or ISCA, would be preferred)  \nPreferably with at least 3 years experience in a Corporate Tax function, in a MNC or accounting firm \nMeticulous and with attention to details\nHands-on experience (e.g. tax preparation and computation) in above areas.\nStrong written and verbal communication, and interpersonal skills\nExcellent communications and inter-personal skills, and passion to deliver quality work'),
	(945, 'Assistant Manager / Deputy Manager (Database Admin)', '/en/job/493047/assistant-manager-deputy-manager-database-admin', 'Infocomm Technology', '2023-10-31 07:55:00', ' Degree/Diploma in Computing, Computer Science, Computer Engineering, Information Systems or equivalent  Able to work independently; set and meet challenging personal targets; good communication skills  Strong analytical and problem-solving skills  Highly conscientious, meticulous and able to multi-task  Be prepared to work in a team providing 24x7 system support  Possess at least 3 years experience with administering Microsoft SQL Server. Experience with related database high availability such as SQL Server Always On Availability Groups Proficiency in scripting for maintenance and automation.  Any additional experience on other database or replication technologies such as Oracle RDBMS, Oracle RAC, MySQL,   Oracle GoldenGate, Quest SharePlex will be advantageous'),
	(946, 'Senior Manager (Business Development- SEA)', '/en/job/493349/senior-manager-business-development-sea', 'Finance', '2023-09-30 07:55:00', ' Good academic background and possess a degree in Accounting, Business, Economics, Engineering,    Finance, IT or equivalent. Minimum 8-10 years of business development experience, preferably in the Maritime, Supply Chain    services in LLP, 4PL, Integrated Logistics industries Tenacious strategic thinker with an active hands-on approach Possess entrepreneurial drive and sharp business acumen Proven track record to of performing in a fast-paced and complex business environment Strong communications and stakeholders management skills Able to influence and establish credibility with internal and external stakeholders to build   collaborative relationships For mobility, candidate should be immediately available or available within 12-18 months for overseas   posting.'),
	(947, 'Accounts Executive (AP)', '/en/job/493168/accounts-executive-ap', 'Finance', '2023-10-31 07:55:00', 'Diploma in Accountancy or equivalent\nPossess at least 1 year of relevant experience in Accounts Payable\nMeticulous and able to work independently\nGood understanding of AP process and related controls\nExcellent interpersonal and communication skills\nGood team player with a positive customer service mindset\nExperience in using Oracle would be advantageous'),
	(948, 'Civil Technical Officer (Tuas Project Site Management)', '/en/job/493285/civil-technical-officer-tuas-project-site-management', 'Engineering', '2023-12-30 16:00:00', 'Diploma in Civil Engineering or Construction Engineering\nRelevant experience preferred\nKnowledge of Building Information Modeling will be an advantage'),
	(949, 'Undergraduate Scholarship - Infocomm Technology (ICT) Track', '/en/job/493338/undergraduate-scholarship-infocomm-technology-ict-track', 'Scholarship', '2023-10-31 07:55:00', ' High learning agility and strong leadership abilities Excellent analytical, communication and interpersonal skills Embrace a dynamic work environment and international assignments Good academic achievements:Terminal Businesso Pursuing a degree in any disciplineo Willing to perform shift duties during foundation years as part of your professional development Engineeringo Pursuing a degree in Electrical/ Electronics/Mechanical/ Computer and Civil Engineeringo Willing to perform shift duties during foundation years as part of your professional developmento Passion for technology and innovationInfocomm Technologyo Pursuing a degree in Computing/Software/ Information Science/Cyber related disciplines o Passion for a career in infocomm technology space o Willing to perform standby duties during foundation years as part of your professional development\nScholarship Award: Our Scholarship sponsors tertiary education in local universities. The scholarship includes a lump sum grant to cover tuition and other miscellaneous fees Successful applicants will be required to serve a bond with PSA upon completion of their studies'),
	(950, 'Assistant Manager/Deputy Manager (Learning And Organisation Development)', '/en/job/493241/assistant-managerdeputy-manager-learning-and-organisation-development', 'Human Resource', '2023-09-30 07:55:00', ' Possess a degree in Business, HR, Organisation Development, or related disciplines with at least 2 years\' of relevant experience Excellent written and communication skills Good interpersonal skills, self-motivated, energetic with a strong drive for results Able to work independently or in teams as the situation requires, and be highly adaptable to work in a diverse environment Comfortable with doing live facilitation when necessary Resourceful, organised and detail-oriented Experience in stakeholder communication & management, as well as knowledge in multimedia and design will be an advantage'),
	(951, 'System Analyst (RPA)', '/en/job/492920/system-analyst-rpa', 'Infocomm Technology', '2023-10-31 07:55:00', ' possess a degree in Computing, Computer Science, IT or Engineering  experience in programming   able to clarify and document user requirements   strong analytical and problem-solving skills  able to multi-task and work independently in a fast-paced environment  preferably with knowledge on one or more of the following software    tools: UI Path, Power BI, Power Automate, .NET, VB, Excel macros'),
	(952, 'Deputy/ Manager (Enterprise Risk and Resilience)', '/en/job/493334/deputy-manager-enterprise-risk-and-resilience', 'Finance', '2023-12-31 07:55:00', ' University degree holder with at least 4 years of relevant working experience in similar role Possesses extensive knowledge of maritime, logistic, cargo solutions operations Preferably have some exposure to operational risk management or emergency preparedness planning, BCM, crisis management practiced in the maritime or logistic sector Good analytical skills and ability to formulate a strong and coherent narrative in writing.  Solutions-oriented mindset and flexible thinking, with a bent towards practical solutions that are tailored for our operation Organised, delivery focused, detail-oriented and can handle multiple tasks concurrently.  A strong relationship builder who can engage effectively across diverse groups and manage multiple stakeholders comfortably'),
	(953, 'Assistant Operations Executive (Planning)', '/en/job/493328/assistant-operations-executive-planning', 'Operations', '2023-12-31 07:55:00', 'You should have a local polytechnic diploma or GCE A levels with 2 H1 and 2 H2 credits.You must be willing to perform shift duties.'),
	(954, 'HSS Duty Manager', '/en/job/493148/hss-duty-manager', 'HSS SEA', '2023-10-31 07:55:00', 'Possessed a recognised Polytechnic Diploma or Degree with a minimum of 5 years relevant experience\nHolds leadership roles in SCDF or SPF\nSCDF Specialist track preferred (EMT, Hazmat, Marine) or SPF & security related experience preferred\nPossess excellent interpersonal skills to maintain rapport with internal and external parties\nEfficient in administrative skills\nAble to perform shift duties\nCandidates with FSM certification will have an added advantage\nCandidate must be physically fit to perform operational duties\nWilling to work in Tuas'),
	(955, 'Systems Engineer / Assistant Manager / Deputy Manager (Systems)', '/en/job/493310/systems-engineer-assistant-manager-deputy-manager-systems', 'Infocomm Technology', '2023-10-31 07:55:00', ' Degree/Diploma in Computing, Computer Science, Computer Engineering, Information Systems or equivalent Deep passion for working with different types of technologies  Growth mindset to challenge traditional norms and drive changes in work processes with a focus on automation    and delivering solutions as a Service  High desire to learn new tools that will be needed to interact with our software products Willingness to script to automate and embrace Infrastructure as Code practices  Be prepared to work in a team providing 24x7 system supportWe value candidates who have a keen interest in one or more of the following technology areas: Private and Hybrid Cloud  Operating Systems  Infrastructure as Code  Middleware and Web Technologies'),
	(956, 'Assistant Operations Executive [WITH JOINING BONUS]', '/en/job/493298/assistant-operations-executive-with-joining-bonus', 'Operations', '2023-12-31 07:55:00', 'You should have a local polytechnic diploma or GCE A levels with 2 H1 and 2 H2 credits.You must be willing to perform shift duties.'),
	(957, 'Container Handling Specialist (Prime Mover Driver)', '/en/job/492822/container-handling-specialist-prime-mover-driver', 'Operations', '2023-12-31 07:55:00', ' Willing to work on rotating shifts Class 3 license preferred, those without will be given additional training.\n There will be a joining incentive of $2,000 for Singaporeans and Singaporean PRs subject to terms and conditions.'),
	(958, 'Operations Executive', '/en/job/492849/operations-executive', 'Operations', '2023-12-31 07:55:00', ' Degree in any discipline Strong leadership, communication and interpersonal skills Results oriented personality who thrives working in a dynamic environment'),
	(959, 'Emergency Response Specialist', '/en/job/492517/emergency-response-specialist', 'HSS SEA', '2023-12-31 07:55:00', ' Possess NITEC qualifications (N level with relevant experience will be considered) Must have relevant experience in SCDF (NS included) Able to work on shift'),
	(960, 'PSA JUNIOR S.E.A.L Programme', '/en/job/492672/psa-junior-seal-programme', 'Internship', '2023-12-31 07:55:00', ' Computing/Computer Engineering/IT/IS undergraduates currently enrolled at NUS/NTU/SMU/SIT/SUTD Strong academic background Passionate about Technology  Strong communication skills  High learning agility and driven to deliver outstanding results'),
	(961, 'Assistant Technician (1-year contract)', '/en/job/492936/assistant-technician-1year-contract', 'Engineering', '2023-12-30 18:45:00', ' Either Nitec in a non-technical discipline or minimum Sec 4 education Willing to work outdoors and at heights Willing to work on weekends'),
	(962, 'Temp HR Assistant (HR Administration)', '/en/job/493013/temp-hr-assistant-hr-administration', 'Human Resource', '2023-11-30 07:55:00', ' Minimum Diploma Has good communication and interpersonal skills Possesses strong initiative, good planning and follow-up skills, and able to meet deadlines in a fast-paced work environment Organised and has a keen eye for details Able to work independently and in a team Able to start work immediately and work for at least 6 months'),
	(963, 'Engineer (Smart System Solutions  Engineering System)', '/en/job/493282/engineer-smart-system-solutions-engineering-system', 'Engineering', '2023-12-31 07:55:00', 'Degree in Engineering (Electrical/Electronic/Systems) or ICT\nKeen in developing project and vendor management skills in Enterprise Asset Management (EAM) concept and processes\nInterest in system development, process re-engineering, exploration of new technologies and productivity improvement engagement\nKeen in internal and external stakeholder engagement and management\nAble to work under minimum supervision\nGood analytical and problem-solving skills\nStrong leadership, communication, and interpersonal skills'),
	(964, 'Mechanical Engineer (M&E services)', '/en/job/493278/mechanical-engineer-me-services', 'Engineering', '2023-12-31 07:55:00', ' Degree in Mechanical Engineering Familiar with local Code of Practices, Building and Fire Safety Regulations Preferably with experience in the design and/or maintenance of M&E equipment and systems used in buildings'),
	(965, 'Systems Analyst', '/en/job/492560/systems-analyst', 'Infocomm Technology', '2023-10-31 07:55:00', ' Degree in Computing, Computer Science, Computer Engineering, Information Systems or equivalent Able to work independently; set and meet challenging personal targets; good communication skills Proficient in programming (C, C++, JAVA) and relational databases and related scripting (Oracle, SQL) Strong analytical and problem solving skills Highly conscientious, meticulous and able to multi-task Be prepared to work in a team providing 24x7 system support\nThe following will be highly valued:\n Hands on experience in frameworks like Angular, Spring Boot; Cloud Foundry or similar cloud technology. Proficiency in Agile Methodologies, such as Extreme Programming (XP) and Scrum Knowledge of software best practices, like Test-Driven Development (TDD) and Continuous Integration (CI)'),
	(966, 'Systems Analyst/Assistant Manager (Optimization)', '/en/job/492884/systems-analystassistant-manager-optimization', 'Infocomm Technology', '2023-10-31 07:55:00', ' Minimum degree holder with computer science, industrial engineering or     applied mathematics background  good business analysis skills required, i.e. interpreting business needs     and translating them into system requirements  good understanding of knowledge engineering and machine learning     techniques, practical experience is preferred  competencies in IT development and familiar with C++, Java programming     is an advantage  exhibiting a \'can-do\' attitude and self-driven  good verbal and written communication skills   interested in exploring agile development methodology  fresh graduates are welcomed'),
	(967, 'Senior Network Engineer', '/en/job/492897/senior-network-engineer', 'Infocomm Technology', '2023-09-30 04:15:00', 'Bachelor degree in Computer/Electrical/Electronics Engineering or Computer Science cCNP Enterprise certified or equivalent at least 3 years of hands-on experience with Cisco campus and data center network   products in a sizeable enterprise deployment experience in network automation (e.g. Ansible) and network management platform   (e.g. Solarwinds) will be an added advantage strong problem solving and analytical skills excellent verbal and written communication skills and customer service skills ability to thrive under pressure, function and deliver effectively in a fast-paced environment '),
	(968, 'Cybersecurity Operations Executive/Engineer', '/en/job/493209/cybersecurity-operations-executiveengineer', 'Infocomm Technology', '2023-09-30 07:55:00', ' Possess a diploma/degree in Computer Science, Information Technology, Cybersecurity or Computer Engineering.  Minimum 1 year of relevant working experience  Strong communication skills and a good team player  Able to work effectively in a fast-paced environment Candidates who have relevant certification on IT Security/Cybersecurity will have an added advantage'),
	(969, 'Technical Officer (Infrastructure Management)', '/en/job/493242/technical-officer-infrastructure-management', 'Engineering', '2023-12-31 07:55:00', ' Diploma in Civil Engineering, Construction Engineering, Building or Facility Management or related fields'),
	(970, 'HSS Duty Officer', '/en/job/493114/hss-duty-officer', 'HSS SEA', '2023-12-29 07:55:00', 'At least NITEC qualificationsCompleted National Service in SCDF with experience in Fire Stations1+ years of experience in Emergency Response Management or related roles to Emergency Response'),
	(971, 'Engineer (Smart System Solutions  Smart Machine)', '/en/job/493254/engineer-smart-system-solutions-smart-machine', 'Engineering', '2023-12-31 07:55:00', 'Degree in Electrical / Mechatronics / Computer / System Engineering\nKeen interest in Electrical Drives, SCADA, HMI and PLC technology\nKnowledge in Matlab modelling and programming\nKnowledge in network technologies is preferred (Ethernet, TCP/IP, Modbus, Profibus, etc)\nPassionate about technology and innovation\nStrong skills in leadership, communication, teaming, analysis and problem-solving'),
	(972, 'Engineer (Smart System Solutions  Smart Engineering)', '/en/job/493255/engineer-smart-system-solutions-smart-engineering', 'Engineering', '2023-12-31 07:55:00', 'Degree in Electrical / Mechanical / Mechatronics / Computer / System Engineering\nProficient in processing large data sets using programming tools like Python\nKnowledge and experience in database programming language such as SQL/HiveQL, scripting in Linux and data visualization development with tools such as Power BI, is preferred\nKeen to learn advanced analytics techniques on Big Data platforms such as Hadoop\nPassionate about technology and innovation\nStrong skills in leadership, communication, teaming, analysis and problem-solving'),
	(973, 'Civil Engineer / Architect', '/en/job/493224/civil-engineer-architect', 'Engineering', '2023-12-31 07:55:00', 'Degree in Civil Engineering / Environmental Engineering / Architecture\nCompetent in Autodesk Revit, SketchUp and other BIM tools\nPreferably with at least 3 years experience in planning and BIM modelling\nKnowledge of Singapore Green Mark and the Corenet eSubmission System will be an added advantage'),
	(974, 'Service Engineer (Digital Systems)', '/en/job/492869/service-engineer-digital-systems', 'Engineering', '2023-12-31 07:55:00', ' Diploma in Electronics / Mechatronics Engineering Experience in maintenance methodology, network and security system will be an advantage Enjoy working outdoors and at height'),
	(975, 'Service Engineer (Electrical Infrastructure)', '/en/job/493204/service-engineer-electrical-infrastructure', 'Engineering', '2023-12-31 07:55:00', ' Diploma in Electrical Engineering (Power) Experience in high-voltage electrical installations and in the maintenance methodology for electrical installations will be an advantage'),
	(976, 'Service Engineer (M&E Design & Drafting)', '/en/job/493198/service-engineer-me-design-drafting', 'Engineering', '2023-12-31 07:55:00', ' Diploma in Electrical/Mechanical Engineering at least 2 years\' experience drafting M&E building services using CAD/MicroStation system and 3D BIM MEP Modelling using Autodesk Revit Experience in design of building mechanical services Willing to work outdoors'),
	(977, 'Service Engineer (M&E Services - Electrical)', '/en/job/493200/service-engineer-me-services-electrical', 'Engineering', '2023-12-30 19:00:00', ' Diploma in Electrical Engineering Preferably with experience in the design and/or maintenance of electrical building services Holders of Licensed Electrical Worker (LEW) license or personnel who had completed the  igh voltage operation for engineers course will have an advantage'),
	(978, 'Assistant Manager/Engineer (OT Security Technology & Development)', '/en/job/493052/assistant-managerengineer-ot-security-technology-development', 'Engineering', '2023-12-31 07:55:00', 'Possesses a degree in Electrical & Electronics Engineering, Computer Engineering, Computer Science, Cybersecurity, Information Security or equivalent\nExperience in OT/ICS environments or IT Infrastructure System will be preferred\nPossess of GICSP, CISSP certification would be an advantage\nGood knowledge and understanding of industry OT & IT security standards and principles such as NIST cybersecurity frameworks, IEC 62443 and ISO27001/2\nUpdated on the latest industry OT/ICS security practices and technologies as well as emerging threats and vulnerabilities\nStrong leadership, communication, interpersonal, analytical and problem-solving skills in a fast-moving environment\nGood project management skills and able to work as a team as well as independently\nFresh grad with passion to pursue OT Security are welcome to apply'),
	(979, 'Technical Specialist (Reefer) [With Joining Bonus]', '/en/job/493192/technical-specialist-reefer-with-joining-bonus', 'Engineering', '2023-12-30 18:45:00', ' Higher NITEC or NITEC in an engineering discipline Willing to work on shift'),
	(980, 'Senior Engineer (Substainabillity)', '/en/job/493164/senior-engineer-substainabillity', 'Engineering', '2023-12-31 07:55:00', ' Degree in Mechanical or Electrical Engineering, or related discipline Minimum 3 years of experience in energy or low carbon technologies projects Knowledge of smart grid, battery technologies and energy market will be an added advantage'),
	(981, 'Equipment Planning Assistant (Maintenance Team)', '/en/job/493158/equipment-planning-assistant-maintenance-team', 'Engineering', '2023-12-31 07:55:00', ' NITEC or minimum 3   level credits Familiar with Microsoft Office applications including Excel and Word'),
	(982, 'Equipment Planning Assistant (Recovery Team)', '/en/job/492933/equipment-planning-assistant-recovery-team', 'Engineering', '2023-12-31 07:55:00', ' NITEC or minimum 3   level credits Familiar with Microsoft Office applications including Excel and Word Willing to work 8-hour shift, in office environment'),
	(983, 'Assistant Manager/Engineer (OT Security Governance)', '/en/job/493051/assistant-managerengineer-ot-security-governance', 'Engineering', '2023-12-31 07:55:00', 'Possess a degree in Computer Engineering, Computer Science, Cybersecurity, Information Security, Electrical & Electronics Engineering or equivalent\nCybersecurity Experience in OT/ICS environments will be preferred\nPossess of GICSP, CISSP, CISA, CISM certification would be an advantage\nGood knowledge and understanding of industry OT & IT security standards and principles such as NIST cybersecurity frameworks, IEC 62443 and ISO27001/2\nStrong leadership, communication, interpersonal, analytical and problem-solving skills in a fast-moving environment\nGood project management skills and able to work as a team as well as independently.\nFresh graduates with passion to pursue OT Security are welcome to apply'),
	(984, 'Senior/Technical Specialist (Quality Management)', '/en/job/492641/seniortechnical-specialist-quality-management', 'Engineering', '2023-12-31 07:55:00', ' Higher NITEC / NITEC in Mechanical Technology or equivalent 3 years\' experience in NDT works Possess NDT Level 2 Certificate in MPT Those with NDT Level 2 Certificate in UT and PT or welding experience will have an added advantage'),
	(985, 'Electrical Engineer (Digital Systems)', '/en/job/492676/electrical-engineer-digital-systems', 'Engineering', '2023-12-31 07:55:00', ' 燚egree in Electrical or Electronics Engineering preference will be given to those with relevant working experience on   digital systems'),
	(986, 'Technical Specialist (Electrical Network) [With Joining Bonus]', '/en/job/492992/technical-specialist-electrical-network-with-joining-bonus', 'Engineering', '2023-12-31 07:55:00', ' Higher NITEC in Electrical Engineering, NITEC in Electrical Technology (Power & Control) or Integrated Mechanical & Electrical Design Willing to work outdoors and at heights'),
	(987, 'Manager/ Senior Engineer (Autonomous Vehicle)', '/en/job/493018/manager-senior-engineer-autonomous-vehicle', 'Engineering', '2023-12-31 07:55:00', ' A good degree in Mechanical or Electrical/Electronic Engineering; and preferably with a Master  degree in Autonomous Vehicle or related specialisation.\n Those with experience in autonomous vehicle technology and testing (eg sensors, automotive hardware, control systems, fleet management software) and with knowledge of software systems and application development will have an advantage.\nPosition title will commensurate with relevant experience.'),
	(988, 'Engineer', '/en/job/492646/engineer', 'Engineering', '2023-12-31 07:55:00', ' Degree in Electrical / Mechanical / Computer / System Engineering  Passionate about technology and innovation  Good analytical and problem-solving skills  Strong leadership, communication and interpersonal skills Enjoy working outdoors and at height'),
	(989, 'Technical Specialist / Assistant Service Engineer (Equipment Engineering) [With Joining Bonus]', '/en/job/492921/technical-specialist-assistant-service-engineer-equipment-engineering-with-joining-bonus', 'Engineering', '2023-12-31 07:55:00', ' NITEC/Higher Nitec/Diploma in a technical discipline  Those without the stipulated qualifications but with related technical experience are also welcome to apply Willing to work outdoors, at heights and on weekends'),
	(990, 'Technical Specialist (Digital Systems) [With Joining Bonus]', '/en/job/492925/technical-specialist-digital-systems-with-joining-bonus', 'Engineering', '2023-12-31 07:55:00', ' At least NITEC/Higher NITEC in a technical discipline Willing to work outdoors and at heights Experience in maintenance methodology will be an advantage'),
	(991, 'Senior Engineer (Smart System Solutions-Smart Engineering)', '/en/job/493088/senior-engineer-smart-system-solutionssmart-engineering', 'Engineering', '2023-12-30 16:00:00', ' Degree in Electrical / Computer / Mechanical / System Engineering Proficient in processing large data sets using programming tools such as Python Knowledge and experience in database programming language like SQL/HiveQL, scripting in Linux and data visualization development with tools such as Power BI, is preferred Passionate about technology and innovation, and keen on advanced analytics techniques'),
	(992, 'Inventory Management Assistant', '/en/job/493098/inventory-management-assistant', 'Engineering', '2023-12-31 07:55:00', ' NITEC in Engineering, Logistics / Supply Chain or equivalent Proficient in Microsoft Office applications like Excel and Word At least 2 years of working experience in the logistic/warehouse field; and familiar with modern warehousing practices and method'),
	(993, 'Principal / Senior Electrical Engineer (Energy Infrastructure)', '/en/job/493068/principal-senior-electrical-engineer-energy-infrastructure', 'Engineering', '2023-12-31 07:55:00', ' Degree in Electrical Engineering with at least 8 years of relevant experience. Strong knowledge of, and hands-on experience in, HV and LV electrical distribution network installation and maintenance. Professional Engineer certification or Licensed Electrical Worker/Engineer will have an advantage.'),
	(994, 'Technical Specialist / Assistant Technician (Welding)', '/en/job/492985/technical-specialist-assistant-technician-welding', 'Engineering', '2023-12-31 07:55:00', '  Possess a welding certificate of 3G or above  At least 3 years experience as a welder in a heavy industry environment  Preferably has NTC 2 or NITEC qualifications  Able to work outdoors and on weekends'),
	(995, 'Senior HR Executive/Assistant Manager (Staff Benefits)', '/en/job/492907/senior-hr-executiveassistant-manager-staff-benefits', 'Human Resource', '2023-10-31 07:55:00', ' possess a good degree in any discipline preferably with 1-2 years of general HR experience with a good understanding    of the Employment Act strong influencing with good communication and interpersonal skills Meticulous and able to work with details able to work very independently in a dynamic environment excellent organising skills (planning, logistics and execution)');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
